name: cicd
on:
  pull_request:

    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: java sdk setup
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Maven Wrapper Executable
        run: chmod +x ./mvnw

      - name: Clean Projectss
        run: ./mvnw clean

